// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectorMessageRQ.proto

package me.bpulse.domain.proto.collector;

public final class CollectorMessageRQ {
  private CollectorMessageRQ() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated string values = 2;
    /**
     * <code>repeated string values = 2;</code>
     */
    java.util.List<java.lang.String>
    getValuesList();
    /**
     * <code>repeated string values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 2;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 2;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code collector.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessage
      implements ValueOrBuilder {
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Value(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Value defaultInstance;
    public static Value getDefaultInstance() {
      return defaultInstance;
    }

    public Value getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              values_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Value_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder.class);
    }

    public static com.google.protobuf.Parser<Value> PARSER =
        new com.google.protobuf.AbstractParser<Value>() {
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Value(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.util.List<java.lang.String>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private void initFields() {
      name_ = "";
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(2, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.collector.CollectorMessageRQ.Value prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code collector.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Value_descriptor;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value getDefaultInstanceForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.getDefaultInstance();
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value build() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value buildPartial() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Value result = new me.bpulse.domain.proto.collector.CollectorMessageRQ.Value(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(
              values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.collector.CollectorMessageRQ.Value) {
          return mergeFrom((me.bpulse.domain.proto.collector.CollectorMessageRQ.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.collector.CollectorMessageRQ.Value other) {
        if (other == me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.collector.CollectorMessageRQ.Value) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated string values = 2;
      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.util.List<java.lang.String>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        super.addAll(values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:collector.Value)
    }

    static {
      defaultInstance = new Value(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:collector.Value)
  }

  public interface PulseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string typeId = 1;
    /**
     * <code>required string typeId = 1;</code>
     */
    boolean hasTypeId();
    /**
     * <code>required string typeId = 1;</code>
     */
    java.lang.String getTypeId();
    /**
     * <code>required string typeId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeIdBytes();

    // required string instanceId = 2;
    /**
     * <code>required string instanceId = 2;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>required string instanceId = 2;</code>
     */
    java.lang.String getInstanceId();
    /**
     * <code>required string instanceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstanceIdBytes();

    // required int64 time = 3;
    /**
     * <code>required int64 time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 3;</code>
     */
    long getTime();

    // repeated .collector.Value values = 4;
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> 
        getValuesList();
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    me.bpulse.domain.proto.collector.CollectorMessageRQ.Value getValues(int index);
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code collector.Pulse}
   */
  public static final class Pulse extends
      com.google.protobuf.GeneratedMessage
      implements PulseOrBuilder {
    // Use Pulse.newBuilder() to construct.
    private Pulse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pulse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pulse defaultInstance;
    public static Pulse getDefaultInstance() {
      return defaultInstance;
    }

    public Pulse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pulse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              typeId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              instanceId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              time_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                values_ = new java.util.ArrayList<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value>();
                mutable_bitField0_ |= 0x00000008;
              }
              values_.add(input.readMessage(me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Pulse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Pulse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder.class);
    }

    public static com.google.protobuf.Parser<Pulse> PARSER =
        new com.google.protobuf.AbstractParser<Pulse>() {
      public Pulse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pulse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pulse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string typeId = 1;
    public static final int TYPEID_FIELD_NUMBER = 1;
    private java.lang.Object typeId_;
    /**
     * <code>required string typeId = 1;</code>
     */
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string typeId = 1;</code>
     */
    public java.lang.String getTypeId() {
      java.lang.Object ref = typeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string typeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeIdBytes() {
      java.lang.Object ref = typeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string instanceId = 2;
    public static final int INSTANCEID_FIELD_NUMBER = 2;
    private java.lang.Object instanceId_;
    /**
     * <code>required string instanceId = 2;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string instanceId = 2;</code>
     */
    public java.lang.String getInstanceId() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instanceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string instanceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceIdBytes() {
      java.lang.Object ref = instanceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 time = 3;
    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>required int64 time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    // repeated .collector.Value values = 4;
    public static final int VALUES_FIELD_NUMBER = 4;
    private java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> values_;
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    public java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .collector.Value values = 4;</code>
     */
    public me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private void initFields() {
      typeId_ = "";
      instanceId_ = "";
      time_ = 0L;
      values_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInstanceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getValuesCount(); i++) {
        if (!getValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, time_);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(4, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInstanceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code collector.Pulse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Pulse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Pulse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_Pulse_descriptor;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse getDefaultInstanceForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.getDefaultInstance();
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse build() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse buildPartial() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse result = new me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instanceId_ = instanceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse) {
          return mergeFrom((me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse other) {
        if (other == me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.getDefaultInstance()) return this;
        if (other.hasTypeId()) {
          bitField0_ |= 0x00000001;
          typeId_ = other.typeId_;
          onChanged();
        }
        if (other.hasInstanceId()) {
          bitField0_ |= 0x00000002;
          instanceId_ = other.instanceId_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000008);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTypeId()) {
          
          return false;
        }
        if (!hasInstanceId()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        for (int i = 0; i < getValuesCount(); i++) {
          if (!getValues(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string typeId = 1;
      private java.lang.Object typeId_ = "";
      /**
       * <code>required string typeId = 1;</code>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public java.lang.String getTypeId() {
        java.lang.Object ref = typeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          typeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeIdBytes() {
        java.lang.Object ref = typeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder setTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeId_ = getDefaultInstance().getTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder setTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }

      // required string instanceId = 2;
      private java.lang.Object instanceId_ = "";
      /**
       * <code>required string instanceId = 2;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string instanceId = 2;</code>
       */
      public java.lang.String getInstanceId() {
        java.lang.Object ref = instanceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          instanceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string instanceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceIdBytes() {
        java.lang.Object ref = instanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string instanceId = 2;</code>
       */
      public Builder setInstanceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string instanceId = 2;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceId_ = getDefaultInstance().getInstanceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string instanceId = 2;</code>
       */
      public Builder setInstanceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instanceId_ = value;
        onChanged();
        return this;
      }

      // required int64 time = 3;
      private long time_ ;
      /**
       * <code>required int64 time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        onChanged();
        return this;
      }

      // repeated .collector.Value values = 4;
      private java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          values_ = new java.util.ArrayList<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value>(values_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Value, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder setValues(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder setValues(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder addValues(me.bpulse.domain.proto.collector.CollectorMessageRQ.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder addValues(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder addValues(
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder addValues(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.Value> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          super.addAll(values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .collector.Value values = 4;</code>
       */
      public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Value, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              me.bpulse.domain.proto.collector.CollectorMessageRQ.Value, me.bpulse.domain.proto.collector.CollectorMessageRQ.Value.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.ValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:collector.Pulse)
    }

    static {
      defaultInstance = new Pulse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:collector.Pulse)
  }

  public interface PulsesRQOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string version = 1;
    /**
     * <code>required string version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>required string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    // repeated .collector.Pulse pulse = 2;
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> 
        getPulseList();
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse getPulse(int index);
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    int getPulseCount();
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder> 
        getPulseOrBuilderList();
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder getPulseOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code collector.PulsesRQ}
   */
  public static final class PulsesRQ extends
      com.google.protobuf.GeneratedMessage
      implements PulsesRQOrBuilder {
    // Use PulsesRQ.newBuilder() to construct.
    private PulsesRQ(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PulsesRQ(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PulsesRQ defaultInstance;
    public static PulsesRQ getDefaultInstance() {
      return defaultInstance;
    }

    public PulsesRQ getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PulsesRQ(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              version_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pulse_ = new java.util.ArrayList<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse>();
                mutable_bitField0_ |= 0x00000002;
              }
              pulse_.add(input.readMessage(me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pulse_ = java.util.Collections.unmodifiableList(pulse_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_PulsesRQ_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_PulsesRQ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.Builder.class);
    }

    public static com.google.protobuf.Parser<PulsesRQ> PARSER =
        new com.google.protobuf.AbstractParser<PulsesRQ>() {
      public PulsesRQ parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PulsesRQ(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PulsesRQ> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private java.lang.Object version_;
    /**
     * <code>required string version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .collector.Pulse pulse = 2;
    public static final int PULSE_FIELD_NUMBER = 2;
    private java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> pulse_;
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> getPulseList() {
      return pulse_;
    }
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    public java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder> 
        getPulseOrBuilderList() {
      return pulse_;
    }
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    public int getPulseCount() {
      return pulse_.size();
    }
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse getPulse(int index) {
      return pulse_.get(index);
    }
    /**
     * <code>repeated .collector.Pulse pulse = 2;</code>
     */
    public me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder getPulseOrBuilder(
        int index) {
      return pulse_.get(index);
    }

    private void initFields() {
      version_ = "";
      pulse_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPulseCount(); i++) {
        if (!getPulse(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVersionBytes());
      }
      for (int i = 0; i < pulse_.size(); i++) {
        output.writeMessage(2, pulse_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVersionBytes());
      }
      for (int i = 0; i < pulse_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pulse_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code collector.PulsesRQ}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_PulsesRQ_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_PulsesRQ_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.class, me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPulseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pulseBuilder_ == null) {
          pulse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pulseBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.internal_static_collector_PulsesRQ_descriptor;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ getDefaultInstanceForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.getDefaultInstance();
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ build() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ buildPartial() {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ result = new me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (pulseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pulse_ = java.util.Collections.unmodifiableList(pulse_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pulse_ = pulse_;
        } else {
          result.pulse_ = pulseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ) {
          return mergeFrom((me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ other) {
        if (other == me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        if (pulseBuilder_ == null) {
          if (!other.pulse_.isEmpty()) {
            if (pulse_.isEmpty()) {
              pulse_ = other.pulse_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePulseIsMutable();
              pulse_.addAll(other.pulse_);
            }
            onChanged();
          }
        } else {
          if (!other.pulse_.isEmpty()) {
            if (pulseBuilder_.isEmpty()) {
              pulseBuilder_.dispose();
              pulseBuilder_ = null;
              pulse_ = other.pulse_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pulseBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPulseFieldBuilder() : null;
            } else {
              pulseBuilder_.addAllMessages(other.pulse_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        for (int i = 0; i < getPulseCount(); i++) {
          if (!getPulse(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.collector.CollectorMessageRQ.PulsesRQ) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string version = 1;
      private java.lang.Object version_ = "";
      /**
       * <code>required string version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      // repeated .collector.Pulse pulse = 2;
      private java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> pulse_ =
        java.util.Collections.emptyList();
      private void ensurePulseIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pulse_ = new java.util.ArrayList<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse>(pulse_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder> pulseBuilder_;

      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> getPulseList() {
        if (pulseBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pulse_);
        } else {
          return pulseBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public int getPulseCount() {
        if (pulseBuilder_ == null) {
          return pulse_.size();
        } else {
          return pulseBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse getPulse(int index) {
        if (pulseBuilder_ == null) {
          return pulse_.get(index);
        } else {
          return pulseBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder setPulse(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse value) {
        if (pulseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulseIsMutable();
          pulse_.set(index, value);
          onChanged();
        } else {
          pulseBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder setPulse(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder builderForValue) {
        if (pulseBuilder_ == null) {
          ensurePulseIsMutable();
          pulse_.set(index, builderForValue.build());
          onChanged();
        } else {
          pulseBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder addPulse(me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse value) {
        if (pulseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulseIsMutable();
          pulse_.add(value);
          onChanged();
        } else {
          pulseBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder addPulse(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse value) {
        if (pulseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulseIsMutable();
          pulse_.add(index, value);
          onChanged();
        } else {
          pulseBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder addPulse(
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder builderForValue) {
        if (pulseBuilder_ == null) {
          ensurePulseIsMutable();
          pulse_.add(builderForValue.build());
          onChanged();
        } else {
          pulseBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder addPulse(
          int index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder builderForValue) {
        if (pulseBuilder_ == null) {
          ensurePulseIsMutable();
          pulse_.add(index, builderForValue.build());
          onChanged();
        } else {
          pulseBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder addAllPulse(
          java.lang.Iterable<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse> values) {
        if (pulseBuilder_ == null) {
          ensurePulseIsMutable();
          super.addAll(values, pulse_);
          onChanged();
        } else {
          pulseBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder clearPulse() {
        if (pulseBuilder_ == null) {
          pulse_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pulseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public Builder removePulse(int index) {
        if (pulseBuilder_ == null) {
          ensurePulseIsMutable();
          pulse_.remove(index);
          onChanged();
        } else {
          pulseBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder getPulseBuilder(
          int index) {
        return getPulseFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder getPulseOrBuilder(
          int index) {
        if (pulseBuilder_ == null) {
          return pulse_.get(index);  } else {
          return pulseBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public java.util.List<? extends me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder> 
           getPulseOrBuilderList() {
        if (pulseBuilder_ != null) {
          return pulseBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pulse_);
        }
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder addPulseBuilder() {
        return getPulseFieldBuilder().addBuilder(
            me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.getDefaultInstance());
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder addPulseBuilder(
          int index) {
        return getPulseFieldBuilder().addBuilder(
            index, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.getDefaultInstance());
      }
      /**
       * <code>repeated .collector.Pulse pulse = 2;</code>
       */
      public java.util.List<me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder> 
           getPulseBuilderList() {
        return getPulseFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder> 
          getPulseFieldBuilder() {
        if (pulseBuilder_ == null) {
          pulseBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse, me.bpulse.domain.proto.collector.CollectorMessageRQ.Pulse.Builder, me.bpulse.domain.proto.collector.CollectorMessageRQ.PulseOrBuilder>(
                  pulse_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pulse_ = null;
        }
        return pulseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:collector.PulsesRQ)
    }

    static {
      defaultInstance = new PulsesRQ(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:collector.PulsesRQ)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_collector_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_collector_Value_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_collector_Pulse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_collector_Pulse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_collector_PulsesRQ_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_collector_PulsesRQ_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030CollectorMessageRQ.proto\022\tcollector\"%\n" +
      "\005Value\022\014\n\004name\030\001 \002(\t\022\016\n\006values\030\002 \003(\t\"[\n\005" +
      "Pulse\022\016\n\006typeId\030\001 \002(\t\022\022\n\ninstanceId\030\002 \002(" +
      "\t\022\014\n\004time\030\003 \002(\003\022 \n\006values\030\004 \003(\0132\020.collec" +
      "tor.Value\"<\n\010PulsesRQ\022\017\n\007version\030\001 \002(\t\022\037" +
      "\n\005pulse\030\002 \003(\0132\020.collector.PulseB$\n me.bp" +
      "ulse.domain.proto.collectorH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_collector_Value_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_collector_Value_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_collector_Value_descriptor,
              new java.lang.String[] { "Name", "Values", });
          internal_static_collector_Pulse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_collector_Pulse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_collector_Pulse_descriptor,
              new java.lang.String[] { "TypeId", "InstanceId", "Time", "Values", });
          internal_static_collector_PulsesRQ_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_collector_PulsesRQ_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_collector_PulsesRQ_descriptor,
              new java.lang.String[] { "Version", "Pulse", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
