// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectorMessageRS.proto

package me.bpulse.domain.proto.collector;

public final class CollectorMessageRS {
  private CollectorMessageRS() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PulsesRSOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 rsTime = 1;
    /**
     * <code>required int64 rsTime = 1;</code>
     */
    boolean hasRsTime();
    /**
     * <code>required int64 rsTime = 1;</code>
     */
    long getRsTime();

    // required .collector.PulsesRS.StatusType status = 2 [default = OK];
    /**
     * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
     */
    boolean hasStatus();
    /**
     * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
     */
    me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType getStatus();

    // optional string error = 3;
    /**
     * <code>optional string error = 3;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code collector.PulsesRS}
   */
  public static final class PulsesRS extends
      com.google.protobuf.GeneratedMessage
      implements PulsesRSOrBuilder {
    // Use PulsesRS.newBuilder() to construct.
    private PulsesRS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PulsesRS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PulsesRS defaultInstance;
    public static PulsesRS getDefaultInstance() {
      return defaultInstance;
    }

    public PulsesRS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PulsesRS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rsTime_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType value = me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.collector.CollectorMessageRS.internal_static_collector_PulsesRS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.collector.CollectorMessageRS.internal_static_collector_PulsesRS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.class, me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.Builder.class);
    }

    public static com.google.protobuf.Parser<PulsesRS> PARSER =
        new com.google.protobuf.AbstractParser<PulsesRS>() {
      public PulsesRS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PulsesRS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PulsesRS> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code collector.PulsesRS.StatusType}
     */
    public enum StatusType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0, 0),
      /**
       * <code>ERROR = 1;</code>
       */
      ERROR(1, 1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>ERROR = 1;</code>
       */
      public static final int ERROR_VALUE = 1;


      public final int getNumber() { return value; }

      public static StatusType valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StatusType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
              public StatusType findValueByNumber(int number) {
                return StatusType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusType[] VALUES = values();

      public static StatusType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StatusType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:collector.PulsesRS.StatusType)
    }

    private int bitField0_;
    // required int64 rsTime = 1;
    public static final int RSTIME_FIELD_NUMBER = 1;
    private long rsTime_;
    /**
     * <code>required int64 rsTime = 1;</code>
     */
    public boolean hasRsTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rsTime = 1;</code>
     */
    public long getRsTime() {
      return rsTime_;
    }

    // required .collector.PulsesRS.StatusType status = 2 [default = OK];
    public static final int STATUS_FIELD_NUMBER = 2;
    private me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType status_;
    /**
     * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
     */
    public me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType getStatus() {
      return status_;
    }

    // optional string error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rsTime_ = 0L;
      status_ = me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType.OK;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRsTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rsTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rsTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code collector.PulsesRS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.collector.CollectorMessageRS.internal_static_collector_PulsesRS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.collector.CollectorMessageRS.internal_static_collector_PulsesRS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.class, me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rsTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType.OK;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRS.internal_static_collector_PulsesRS_descriptor;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS getDefaultInstanceForType() {
        return me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.getDefaultInstance();
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS build() {
        me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS buildPartial() {
        me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS result = new me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rsTime_ = rsTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS) {
          return mergeFrom((me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS other) {
        if (other == me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.getDefaultInstance()) return this;
        if (other.hasRsTime()) {
          setRsTime(other.getRsTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRsTime()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 rsTime = 1;
      private long rsTime_ ;
      /**
       * <code>required int64 rsTime = 1;</code>
       */
      public boolean hasRsTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rsTime = 1;</code>
       */
      public long getRsTime() {
        return rsTime_;
      }
      /**
       * <code>required int64 rsTime = 1;</code>
       */
      public Builder setRsTime(long value) {
        bitField0_ |= 0x00000001;
        rsTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rsTime = 1;</code>
       */
      public Builder clearRsTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rsTime_ = 0L;
        onChanged();
        return this;
      }

      // required .collector.PulsesRS.StatusType status = 2 [default = OK];
      private me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType status_ = me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType.OK;
      /**
       * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
       */
      public me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType getStatus() {
        return status_;
      }
      /**
       * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
       */
      public Builder setStatus(me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .collector.PulsesRS.StatusType status = 2 [default = OK];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = me.bpulse.domain.proto.collector.CollectorMessageRS.PulsesRS.StatusType.OK;
        onChanged();
        return this;
      }

      // optional string error = 3;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:collector.PulsesRS)
    }

    static {
      defaultInstance = new PulsesRS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:collector.PulsesRS)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_collector_PulsesRS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_collector_PulsesRS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030CollectorMessageRS.proto\022\tcollector\"~\n" +
      "\010PulsesRS\022\016\n\006rsTime\030\001 \002(\003\0222\n\006status\030\002 \002(" +
      "\0162\036.collector.PulsesRS.StatusType:\002OK\022\r\n" +
      "\005error\030\003 \001(\t\"\037\n\nStatusType\022\006\n\002OK\020\000\022\t\n\005ER" +
      "ROR\020\001B$\n me.bpulse.domain.proto.collecto" +
      "rH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_collector_PulsesRS_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_collector_PulsesRS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_collector_PulsesRS_descriptor,
              new java.lang.String[] { "RsTime", "Status", "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
