#!/bin/bash

set -e
shopt -s expand_aliases

# Wrap  commands inside containers with all necessary dependencies
MAVEN_OPTS='-Xms256m -Xmx512m -XX:MaxPermSize=512m -XX:PermSize=128m'
alias  mvn='docker run -it -e MAVEN_OPTS="$MAVEN_OPTS" --rm -v ~/.m2:/root/.m2 -v $(pwd):/local/git harbur/docker-java7-maven-protobuf mvn'

mvn clean install
