// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KPIPulseValuesMessageRS.proto

package me.bpulse.domain.proto.kpi.pulse;

public final class KPIPulseValuesMessageRS {
  private KPIPulseValuesMessageRS() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated string values = 2;
    /**
     * <code>repeated string values = 2;</code>
     */
    java.util.List<java.lang.String>
    getValuesList();
    /**
     * <code>repeated string values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 2;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 2;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code pulse.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessage
      implements ValueOrBuilder {
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Value(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Value defaultInstance;
    public static Value getDefaultInstance() {
      return defaultInstance;
    }

    public Value getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              values_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Value_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder.class);
    }

    public static com.google.protobuf.Parser<Value> PARSER =
        new com.google.protobuf.AbstractParser<Value>() {
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Value(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.util.List<java.lang.String>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private void initFields() {
      name_ = "";
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(2, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pulse.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Value_descriptor;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value getDefaultInstanceForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.getDefaultInstance();
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value build() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value buildPartial() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value result = new me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.UnmodifiableLazyStringList(
              values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value) {
          return mergeFrom((me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value other) {
        if (other == me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated string values = 2;
      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.util.List<java.lang.String>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        super.addAll(values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pulse.Value)
    }

    static {
      defaultInstance = new Value(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pulse.Value)
  }

  public interface PulseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string typeId = 1;
    /**
     * <code>required string typeId = 1;</code>
     */
    boolean hasTypeId();
    /**
     * <code>required string typeId = 1;</code>
     */
    java.lang.String getTypeId();
    /**
     * <code>required string typeId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeIdBytes();

    // repeated .pulse.Value values = 2;
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> 
        getValuesList();
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value getValues(int index);
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder> 
        getValuesOrBuilderList();
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder getValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pulse.Pulse}
   */
  public static final class Pulse extends
      com.google.protobuf.GeneratedMessage
      implements PulseOrBuilder {
    // Use Pulse.newBuilder() to construct.
    private Pulse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pulse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pulse defaultInstance;
    public static Pulse getDefaultInstance() {
      return defaultInstance;
    }

    public Pulse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pulse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              typeId_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                values_ = new java.util.ArrayList<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value>();
                mutable_bitField0_ |= 0x00000002;
              }
              values_.add(input.readMessage(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Pulse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Pulse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder.class);
    }

    public static com.google.protobuf.Parser<Pulse> PARSER =
        new com.google.protobuf.AbstractParser<Pulse>() {
      public Pulse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pulse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pulse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string typeId = 1;
    public static final int TYPEID_FIELD_NUMBER = 1;
    private java.lang.Object typeId_;
    /**
     * <code>required string typeId = 1;</code>
     */
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string typeId = 1;</code>
     */
    public java.lang.String getTypeId() {
      java.lang.Object ref = typeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string typeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeIdBytes() {
      java.lang.Object ref = typeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .pulse.Value values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> values_;
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> getValuesList() {
      return values_;
    }
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    public java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder> 
        getValuesOrBuilderList() {
      return values_;
    }
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated .pulse.Value values = 2;</code>
     */
    public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder getValuesOrBuilder(
        int index) {
      return values_.get(index);
    }

    private void initFields() {
      typeId_ = "";
      values_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getValuesCount(); i++) {
        if (!getValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeIdBytes());
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeMessage(2, values_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeIdBytes());
      }
      for (int i = 0; i < values_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, values_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pulse.Pulse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Pulse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Pulse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_Pulse_descriptor;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse getDefaultInstanceForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.getDefaultInstance();
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse build() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse buildPartial() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse result = new me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeId_ = typeId_;
        if (valuesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            values_ = java.util.Collections.unmodifiableList(values_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.values_ = values_;
        } else {
          result.values_ = valuesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse) {
          return mergeFrom((me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse other) {
        if (other == me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.getDefaultInstance()) return this;
        if (other.hasTypeId()) {
          bitField0_ |= 0x00000001;
          typeId_ = other.typeId_;
          onChanged();
        }
        if (valuesBuilder_ == null) {
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
        } else {
          if (!other.values_.isEmpty()) {
            if (valuesBuilder_.isEmpty()) {
              valuesBuilder_.dispose();
              valuesBuilder_ = null;
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000002);
              valuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValuesFieldBuilder() : null;
            } else {
              valuesBuilder_.addAllMessages(other.values_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTypeId()) {
          
          return false;
        }
        for (int i = 0; i < getValuesCount(); i++) {
          if (!getValues(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string typeId = 1;
      private java.lang.Object typeId_ = "";
      /**
       * <code>required string typeId = 1;</code>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public java.lang.String getTypeId() {
        java.lang.Object ref = typeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          typeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeIdBytes() {
        java.lang.Object ref = typeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder setTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeId_ = getDefaultInstance().getTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>required string typeId = 1;</code>
       */
      public Builder setTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }

      // repeated .pulse.Value values = 2;
      private java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> values_ =
        java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new java.util.ArrayList<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value>(values_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder> valuesBuilder_;

      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> getValuesList() {
        if (valuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(values_);
        } else {
          return valuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public int getValuesCount() {
        if (valuesBuilder_ == null) {
          return values_.size();
        } else {
          return valuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value getValues(int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);
        } else {
          return valuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder setValues(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.set(index, value);
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder setValues(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.set(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder addValues(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder addValues(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value value) {
        if (valuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValuesIsMutable();
          values_.add(index, value);
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder addValues(
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder addValues(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder builderForValue) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.add(index, builderForValue.build());
          onChanged();
        } else {
          valuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value> values) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          super.addAll(values, values_);
          onChanged();
        } else {
          valuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder clearValues() {
        if (valuesBuilder_ == null) {
          values_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          valuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public Builder removeValues(int index) {
        if (valuesBuilder_ == null) {
          ensureValuesIsMutable();
          values_.remove(index);
          onChanged();
        } else {
          valuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder getValuesBuilder(
          int index) {
        return getValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder getValuesOrBuilder(
          int index) {
        if (valuesBuilder_ == null) {
          return values_.get(index);  } else {
          return valuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder> 
           getValuesOrBuilderList() {
        if (valuesBuilder_ != null) {
          return valuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(values_);
        }
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder addValuesBuilder() {
        return getValuesFieldBuilder().addBuilder(
            me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder addValuesBuilder(
          int index) {
        return getValuesFieldBuilder().addBuilder(
            index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.getDefaultInstance());
      }
      /**
       * <code>repeated .pulse.Value values = 2;</code>
       */
      public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder> 
           getValuesBuilderList() {
        return getValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder> 
          getValuesFieldBuilder() {
        if (valuesBuilder_ == null) {
          valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Value.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.ValueOrBuilder>(
                  values_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          values_ = null;
        }
        return valuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pulse.Pulse)
    }

    static {
      defaultInstance = new Pulse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pulse.Pulse)
  }

  public interface KPIPulseValuesRSOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .pulse.Pulse pulses = 1;
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> 
        getPulsesList();
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse getPulses(int index);
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    int getPulsesCount();
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder> 
        getPulsesOrBuilderList();
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder getPulsesOrBuilder(
        int index);

    // required int64 rsTime = 2;
    /**
     * <code>required int64 rsTime = 2;</code>
     */
    boolean hasRsTime();
    /**
     * <code>required int64 rsTime = 2;</code>
     */
    long getRsTime();

    // required int64 totalPulses = 3;
    /**
     * <code>required int64 totalPulses = 3;</code>
     */
    boolean hasTotalPulses();
    /**
     * <code>required int64 totalPulses = 3;</code>
     */
    long getTotalPulses();

    // required int64 totalPulsesDisplayed = 4;
    /**
     * <code>required int64 totalPulsesDisplayed = 4;</code>
     */
    boolean hasTotalPulsesDisplayed();
    /**
     * <code>required int64 totalPulsesDisplayed = 4;</code>
     */
    long getTotalPulsesDisplayed();

    // required int64 totalDisplayPulses = 5;
    /**
     * <code>required int64 totalDisplayPulses = 5;</code>
     */
    boolean hasTotalDisplayPulses();
    /**
     * <code>required int64 totalDisplayPulses = 5;</code>
     */
    long getTotalDisplayPulses();
  }
  /**
   * Protobuf type {@code pulse.KPIPulseValuesRS}
   */
  public static final class KPIPulseValuesRS extends
      com.google.protobuf.GeneratedMessage
      implements KPIPulseValuesRSOrBuilder {
    // Use KPIPulseValuesRS.newBuilder() to construct.
    private KPIPulseValuesRS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KPIPulseValuesRS(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KPIPulseValuesRS defaultInstance;
    public static KPIPulseValuesRS getDefaultInstance() {
      return defaultInstance;
    }

    public KPIPulseValuesRS getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KPIPulseValuesRS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pulses_ = new java.util.ArrayList<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse>();
                mutable_bitField0_ |= 0x00000001;
              }
              pulses_.add(input.readMessage(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              rsTime_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              totalPulses_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              totalPulsesDisplayed_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              totalDisplayPulses_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pulses_ = java.util.Collections.unmodifiableList(pulses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_KPIPulseValuesRS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_KPIPulseValuesRS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.Builder.class);
    }

    public static com.google.protobuf.Parser<KPIPulseValuesRS> PARSER =
        new com.google.protobuf.AbstractParser<KPIPulseValuesRS>() {
      public KPIPulseValuesRS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KPIPulseValuesRS(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KPIPulseValuesRS> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .pulse.Pulse pulses = 1;
    public static final int PULSES_FIELD_NUMBER = 1;
    private java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> pulses_;
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> getPulsesList() {
      return pulses_;
    }
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    public java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder> 
        getPulsesOrBuilderList() {
      return pulses_;
    }
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    public int getPulsesCount() {
      return pulses_.size();
    }
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse getPulses(int index) {
      return pulses_.get(index);
    }
    /**
     * <code>repeated .pulse.Pulse pulses = 1;</code>
     */
    public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder getPulsesOrBuilder(
        int index) {
      return pulses_.get(index);
    }

    // required int64 rsTime = 2;
    public static final int RSTIME_FIELD_NUMBER = 2;
    private long rsTime_;
    /**
     * <code>required int64 rsTime = 2;</code>
     */
    public boolean hasRsTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rsTime = 2;</code>
     */
    public long getRsTime() {
      return rsTime_;
    }

    // required int64 totalPulses = 3;
    public static final int TOTALPULSES_FIELD_NUMBER = 3;
    private long totalPulses_;
    /**
     * <code>required int64 totalPulses = 3;</code>
     */
    public boolean hasTotalPulses() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 totalPulses = 3;</code>
     */
    public long getTotalPulses() {
      return totalPulses_;
    }

    // required int64 totalPulsesDisplayed = 4;
    public static final int TOTALPULSESDISPLAYED_FIELD_NUMBER = 4;
    private long totalPulsesDisplayed_;
    /**
     * <code>required int64 totalPulsesDisplayed = 4;</code>
     */
    public boolean hasTotalPulsesDisplayed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 totalPulsesDisplayed = 4;</code>
     */
    public long getTotalPulsesDisplayed() {
      return totalPulsesDisplayed_;
    }

    // required int64 totalDisplayPulses = 5;
    public static final int TOTALDISPLAYPULSES_FIELD_NUMBER = 5;
    private long totalDisplayPulses_;
    /**
     * <code>required int64 totalDisplayPulses = 5;</code>
     */
    public boolean hasTotalDisplayPulses() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 totalDisplayPulses = 5;</code>
     */
    public long getTotalDisplayPulses() {
      return totalDisplayPulses_;
    }

    private void initFields() {
      pulses_ = java.util.Collections.emptyList();
      rsTime_ = 0L;
      totalPulses_ = 0L;
      totalPulsesDisplayed_ = 0L;
      totalDisplayPulses_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRsTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalPulses()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalPulsesDisplayed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalDisplayPulses()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPulsesCount(); i++) {
        if (!getPulses(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pulses_.size(); i++) {
        output.writeMessage(1, pulses_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, rsTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, totalPulses_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, totalPulsesDisplayed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, totalDisplayPulses_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pulses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pulses_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, rsTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, totalPulses_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, totalPulsesDisplayed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, totalDisplayPulses_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pulse.KPIPulseValuesRS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_KPIPulseValuesRS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_KPIPulseValuesRS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.class, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.Builder.class);
      }

      // Construct using me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPulsesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pulsesBuilder_ == null) {
          pulses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pulsesBuilder_.clear();
        }
        rsTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalPulses_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPulsesDisplayed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        totalDisplayPulses_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.internal_static_pulse_KPIPulseValuesRS_descriptor;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS getDefaultInstanceForType() {
        return me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.getDefaultInstance();
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS build() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS buildPartial() {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS result = new me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (pulsesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pulses_ = java.util.Collections.unmodifiableList(pulses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pulses_ = pulses_;
        } else {
          result.pulses_ = pulsesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rsTime_ = rsTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalPulses_ = totalPulses_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.totalPulsesDisplayed_ = totalPulsesDisplayed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totalDisplayPulses_ = totalDisplayPulses_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS) {
          return mergeFrom((me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS other) {
        if (other == me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS.getDefaultInstance()) return this;
        if (pulsesBuilder_ == null) {
          if (!other.pulses_.isEmpty()) {
            if (pulses_.isEmpty()) {
              pulses_ = other.pulses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePulsesIsMutable();
              pulses_.addAll(other.pulses_);
            }
            onChanged();
          }
        } else {
          if (!other.pulses_.isEmpty()) {
            if (pulsesBuilder_.isEmpty()) {
              pulsesBuilder_.dispose();
              pulsesBuilder_ = null;
              pulses_ = other.pulses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pulsesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPulsesFieldBuilder() : null;
            } else {
              pulsesBuilder_.addAllMessages(other.pulses_);
            }
          }
        }
        if (other.hasRsTime()) {
          setRsTime(other.getRsTime());
        }
        if (other.hasTotalPulses()) {
          setTotalPulses(other.getTotalPulses());
        }
        if (other.hasTotalPulsesDisplayed()) {
          setTotalPulsesDisplayed(other.getTotalPulsesDisplayed());
        }
        if (other.hasTotalDisplayPulses()) {
          setTotalDisplayPulses(other.getTotalDisplayPulses());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRsTime()) {
          
          return false;
        }
        if (!hasTotalPulses()) {
          
          return false;
        }
        if (!hasTotalPulsesDisplayed()) {
          
          return false;
        }
        if (!hasTotalDisplayPulses()) {
          
          return false;
        }
        for (int i = 0; i < getPulsesCount(); i++) {
          if (!getPulses(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.KPIPulseValuesRS) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .pulse.Pulse pulses = 1;
      private java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> pulses_ =
        java.util.Collections.emptyList();
      private void ensurePulsesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pulses_ = new java.util.ArrayList<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse>(pulses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder> pulsesBuilder_;

      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> getPulsesList() {
        if (pulsesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pulses_);
        } else {
          return pulsesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public int getPulsesCount() {
        if (pulsesBuilder_ == null) {
          return pulses_.size();
        } else {
          return pulsesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse getPulses(int index) {
        if (pulsesBuilder_ == null) {
          return pulses_.get(index);
        } else {
          return pulsesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder setPulses(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse value) {
        if (pulsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulsesIsMutable();
          pulses_.set(index, value);
          onChanged();
        } else {
          pulsesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder setPulses(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder builderForValue) {
        if (pulsesBuilder_ == null) {
          ensurePulsesIsMutable();
          pulses_.set(index, builderForValue.build());
          onChanged();
        } else {
          pulsesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder addPulses(me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse value) {
        if (pulsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulsesIsMutable();
          pulses_.add(value);
          onChanged();
        } else {
          pulsesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder addPulses(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse value) {
        if (pulsesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePulsesIsMutable();
          pulses_.add(index, value);
          onChanged();
        } else {
          pulsesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder addPulses(
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder builderForValue) {
        if (pulsesBuilder_ == null) {
          ensurePulsesIsMutable();
          pulses_.add(builderForValue.build());
          onChanged();
        } else {
          pulsesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder addPulses(
          int index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder builderForValue) {
        if (pulsesBuilder_ == null) {
          ensurePulsesIsMutable();
          pulses_.add(index, builderForValue.build());
          onChanged();
        } else {
          pulsesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder addAllPulses(
          java.lang.Iterable<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse> values) {
        if (pulsesBuilder_ == null) {
          ensurePulsesIsMutable();
          super.addAll(values, pulses_);
          onChanged();
        } else {
          pulsesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder clearPulses() {
        if (pulsesBuilder_ == null) {
          pulses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pulsesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public Builder removePulses(int index) {
        if (pulsesBuilder_ == null) {
          ensurePulsesIsMutable();
          pulses_.remove(index);
          onChanged();
        } else {
          pulsesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder getPulsesBuilder(
          int index) {
        return getPulsesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder getPulsesOrBuilder(
          int index) {
        if (pulsesBuilder_ == null) {
          return pulses_.get(index);  } else {
          return pulsesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public java.util.List<? extends me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder> 
           getPulsesOrBuilderList() {
        if (pulsesBuilder_ != null) {
          return pulsesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pulses_);
        }
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder addPulsesBuilder() {
        return getPulsesFieldBuilder().addBuilder(
            me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.getDefaultInstance());
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder addPulsesBuilder(
          int index) {
        return getPulsesFieldBuilder().addBuilder(
            index, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.getDefaultInstance());
      }
      /**
       * <code>repeated .pulse.Pulse pulses = 1;</code>
       */
      public java.util.List<me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder> 
           getPulsesBuilderList() {
        return getPulsesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder> 
          getPulsesFieldBuilder() {
        if (pulsesBuilder_ == null) {
          pulsesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.Pulse.Builder, me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRS.PulseOrBuilder>(
                  pulses_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pulses_ = null;
        }
        return pulsesBuilder_;
      }

      // required int64 rsTime = 2;
      private long rsTime_ ;
      /**
       * <code>required int64 rsTime = 2;</code>
       */
      public boolean hasRsTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 rsTime = 2;</code>
       */
      public long getRsTime() {
        return rsTime_;
      }
      /**
       * <code>required int64 rsTime = 2;</code>
       */
      public Builder setRsTime(long value) {
        bitField0_ |= 0x00000002;
        rsTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rsTime = 2;</code>
       */
      public Builder clearRsTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rsTime_ = 0L;
        onChanged();
        return this;
      }

      // required int64 totalPulses = 3;
      private long totalPulses_ ;
      /**
       * <code>required int64 totalPulses = 3;</code>
       */
      public boolean hasTotalPulses() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 totalPulses = 3;</code>
       */
      public long getTotalPulses() {
        return totalPulses_;
      }
      /**
       * <code>required int64 totalPulses = 3;</code>
       */
      public Builder setTotalPulses(long value) {
        bitField0_ |= 0x00000004;
        totalPulses_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 totalPulses = 3;</code>
       */
      public Builder clearTotalPulses() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalPulses_ = 0L;
        onChanged();
        return this;
      }

      // required int64 totalPulsesDisplayed = 4;
      private long totalPulsesDisplayed_ ;
      /**
       * <code>required int64 totalPulsesDisplayed = 4;</code>
       */
      public boolean hasTotalPulsesDisplayed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 totalPulsesDisplayed = 4;</code>
       */
      public long getTotalPulsesDisplayed() {
        return totalPulsesDisplayed_;
      }
      /**
       * <code>required int64 totalPulsesDisplayed = 4;</code>
       */
      public Builder setTotalPulsesDisplayed(long value) {
        bitField0_ |= 0x00000008;
        totalPulsesDisplayed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 totalPulsesDisplayed = 4;</code>
       */
      public Builder clearTotalPulsesDisplayed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalPulsesDisplayed_ = 0L;
        onChanged();
        return this;
      }

      // required int64 totalDisplayPulses = 5;
      private long totalDisplayPulses_ ;
      /**
       * <code>required int64 totalDisplayPulses = 5;</code>
       */
      public boolean hasTotalDisplayPulses() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 totalDisplayPulses = 5;</code>
       */
      public long getTotalDisplayPulses() {
        return totalDisplayPulses_;
      }
      /**
       * <code>required int64 totalDisplayPulses = 5;</code>
       */
      public Builder setTotalDisplayPulses(long value) {
        bitField0_ |= 0x00000010;
        totalDisplayPulses_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 totalDisplayPulses = 5;</code>
       */
      public Builder clearTotalDisplayPulses() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalDisplayPulses_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pulse.KPIPulseValuesRS)
    }

    static {
      defaultInstance = new KPIPulseValuesRS(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pulse.KPIPulseValuesRS)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pulse_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pulse_Value_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pulse_Pulse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pulse_Pulse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pulse_KPIPulseValuesRS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pulse_KPIPulseValuesRS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035KPIPulseValuesMessageRS.proto\022\005pulse\032\035" +
      "KPIPulseValuesMessageRQ.proto\"%\n\005Value\022\014" +
      "\n\004name\030\001 \002(\t\022\016\n\006values\030\002 \003(\t\"5\n\005Pulse\022\016\n" +
      "\006typeId\030\001 \002(\t\022\034\n\006values\030\002 \003(\0132\014.pulse.Va" +
      "lue\"\217\001\n\020KPIPulseValuesRS\022\034\n\006pulses\030\001 \003(\013" +
      "2\014.pulse.Pulse\022\016\n\006rsTime\030\002 \002(\003\022\023\n\013totalP" +
      "ulses\030\003 \002(\003\022\034\n\024totalPulsesDisplayed\030\004 \002(" +
      "\003\022\032\n\022totalDisplayPulses\030\005 \002(\003B$\n me.bpul" +
      "se.domain.proto.kpi.pulseH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pulse_Value_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pulse_Value_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pulse_Value_descriptor,
              new java.lang.String[] { "Name", "Values", });
          internal_static_pulse_Pulse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pulse_Pulse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pulse_Pulse_descriptor,
              new java.lang.String[] { "TypeId", "Values", });
          internal_static_pulse_KPIPulseValuesRS_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_pulse_KPIPulseValuesRS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pulse_KPIPulseValuesRS_descriptor,
              new java.lang.String[] { "Pulses", "RsTime", "TotalPulses", "TotalPulsesDisplayed", "TotalDisplayPulses", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.bpulse.domain.proto.kpi.pulse.KPIPulseValuesMessageRQ.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
